name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Show xcode version
      run: xcodebuild -version
    - name: Run testing
      run: xcodebuild
        -sdk iphonesimulator
        -configuration Debug
        -scheme Kotori
        build
