name: Unit Test

on:
  workflow_dispatch:

  # push:
  #   branches: [main]

  # pull_request:
  #   branches: [main]

  schedule:
    - cron: "* 3 * * *"

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Setup timezone
        env:
          TZ: 'Asia/Tokyo'

      - uses: actions/checkout@v2

      - name: Show xcode version
        run: xcodebuild -version

      - name: Run testing
        run: xcodebuild
          -sdk iphonesimulator
          -configuration Debug
          -scheme Kotori
          -destination 'platform=iOS Simulator,name=iPhone 12'
          clean test
